### ISSUE TITLE
i got This from time to time 

### ISSUE THREAD

**Issue by MemoMubarak** [Cleveroad/FanLayoutManager#5]
java.lang.NullPointerException
	at android.support.v7.widget.RecyclerView$LayoutManager.getPosition(RecyclerView.java:7187)
	at com.cleveroad.fanlayoutmanager.FanLayoutManager.findCurrentCenterViewPos(FanLayoutManager.java:980)
	at com.cleveroad.fanlayoutmanager.FanLayoutManager.onSaveInstanceState(FanLayoutManager.java:164)
	at android.support.v7.widget.RecyclerView.onSaveInstanceState(RecyclerView.java:1126)
	at android.view.View.dispatchSaveInstanceState(View.java:12922)
	at android.view.ViewGroup.dispatchFreezeSelfOnly(ViewGroup.java:2763)
	at android.support.v7.widget.RecyclerView.dispatchSaveInstanceState(RecyclerView.java:1153)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2749)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2749)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2749)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2749)
	at android.view.View.saveHierarchyState(View.java:12905)
	at com.android.internal.policy.impl.PhoneWindow.saveHierarchyState(PhoneWindow.java:1845)
	at android.app.Activity.onSaveInstanceState(Activity.java:1277)
	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:567)
	at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
	at android.app.Activity.performSaveInstanceState(Activity.java:1226)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1230)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3451)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3510)
	at android.app.ActivityThread.access$1100(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by MemoMubarak** [comment]
Can you explain more please ?
